name: Generate index.json

on:
  push:
    branches:
      - main

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run generate_index.py
        run: python utils/generate_index.py

      - name: Commit and push index.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update index.json [auto]"
          file_pattern: index.json