name: Matrix tests for interfaces

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_call:
    inputs:
      repo:
        description: 'The repo to fetch the test and interfaces definitions from'
        default: ''
        required: false
        type: string
      branch:
        description: 'The branch of the repo to fetch the test and interface definitions from'
        default: ''
        required: false
        type: string
  workflow_dispatch:
    inputs:
      repo:
        description: 'The repo to fetch the test and interfaces definitions from'
        default: ''
        required: false
        type: string
      branch:
        description: 'The branch of the repo to fetch the test and interface definitions from'
        default: ''
        required: false
        type: string

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix_values: ${{ steps.set-matrix.outputs.matrix_values }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set matrix values
        id: set-matrix
        shell: python
        run: |
          import os, pathlib, json
          interfaces = sorted(
              i.name
              for i in pathlib.Path('interfaces').iterdir()
              if i.is_dir()
              and i.name != '__template__'
              and any(p.is_dir() for p in i.glob('v[0-9]*/interface_tests'))
          )
          line = f'matrix_values={json.dumps(interfaces)}'
          print(line)
          with pathlib.Path(os.environ['GITHUB_OUTPUT']).open('a') as f:
              print(line, file=f)

  main:
    name: ${{ matrix.interface }}
    needs: set-matrix
    strategy:
      fail-fast: false
      matrix:
        interface: ${{ fromJSON(needs.set-matrix.outputs.matrix_values) }}
    uses: ./.github/workflows/dispatch-matrix-tests.yaml
    with:
      event: ${{ github.event_name }}
      interface: ${{ matrix.interface }}
      repo: ${{ inputs.repo }}  # empty string is the default value
      branch: ${{ inputs.branch }}  # empty string is the default value
