name: Matrix tests for interfaces

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix_values: ${{ steps.set-matrix.outputs.matrix_values }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set matrix values
        id: set-matrix
        run: |
          interfaces=$(find interfaces -mindepth 1 -maxdepth 1 -type d -not -name "__template__" -printf '%f\n' | jq --raw-input . | jq -c --slurp .)
          echo "matrix_values=${interfaces}" >> $GITHUB_OUTPUT

  main:
    name: ${{ matrix.interface }}
    needs: set-matrix
    strategy:
      fail-fast: false
      matrix:
        interface: ${{ fromJSON(needs.set-matrix.outputs.matrix_values) }}
    uses: ./.github/workflows/dispatch-matrix-tests.yaml
    with:
      interface: ${{ matrix.interface }}
