name: Matrix tests for interfaces

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_call:
    inputs:
      repo:
        description: 'The repo to fetch the test and interfaces definitions from'
        default: ''
        required: false
        type: string
      branch:
        description: 'The branch of the repo to fetch the test and interface definitions from'
        default: ''
        required: false
        type: string
  workflow_dispatch:
    inputs:
      repo:
        description: 'The repo to fetch the test and interfaces definitions from'
        default: ''
        required: false
        type: string
      branch:
        description: 'The branch of the repo to fetch the test and interface definitions from'
        default: ''
        required: false
        type: string

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set matrix values
        id: matrix
        run: |
          interfaces=($(find interfaces -mindepth 1 -maxdepth 1 -type d -not -name "__template__" -printf '%f\n' | sort))
          matrix=()
          for interface in "${interfaces[@]}"; do
            tests=no-tests
            for v in interfaces/$interface/v[0-9]*; do
              if [ -d "$v/interface_tests" ]; then
                tests=has-tests
                break
              fi
            done
            entry=$(jq --null-input --arg i "$interface" --arg t "$tests" '{interface: $i, tests: $t}')
            matrix+=("$entry")
          done
          js=$(printf '%s\n' "${matrix[@]}" | jq --slurp --compact-output '.')
          echo "matrix=$js"
          echo "matrix=$js" >> "$GITHUB_OUTPUT"

  main:
    name: ${{ matrix.interface }}
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    # if: ${{ matrix.tests != 'no-tests' }}  # doesn't work! matrix isn't available when job uses a reusable workflow
    uses: ./.github/workflows/dispatch-matrix-tests.yaml
    with:
      event: ${{ github.event_name }}
      interface: ${{ matrix.interface }}
      repo: ${{ inputs.repo }}  # empty string is the default value
      branch: ${{ inputs.branch }}  # empty string is the default value
